### ISSUE TITLE
Feature: Adding objects to locked containers (dragging)

### ISSUE THREAD

**Issue by elmodor** [drwhut/tabletop-club#110]
**Is your feature request related to a problem? Please describe.**
When locking a containers, you can not drag objects inside anymore (only via the right click menu "add selected object". However, usually you want to lock containers in place so that they don't move around. But you also want to be able to easily store tokens inside them again when they are discarded.

**Describe the solution you'd like**
A container should have a right click option checkbox option: "Add dragged objects while locked"

**Describe alternatives you've considered**
Alternative a checkbox could be added to allow adding objects to the specific locked container. So objects can be added via drag/GUI to locked containers, or they can't be added via dragging/GUI to locked containers.

**Comment by drwhut** [comment]
So I've done some digging, and it turns out the reason containers don't take in items this way when locked is because `RigidBody` nodes in Godot don't emit the `body_entered` signal when in static mode, which is the mode they are in when objects are locked ><

HOWEVER, they DO emit the signal when in kinematic mode, which acts the same way as static mode (as long as no commands are given), which should solve the problem! I'll need to make sure that this doesn't negatively affect anything else in the game before committing to the change, though.

**Comment by drwhut** [comment]
Managed to find a way to get containers to perform collision detection when locked, see the commit for more details!

**Comment by elmodor** [comment]
Sweet, thanks! Seems like a good solution.
