### ISSUE TITLE
Feature: Official Discord Server

### ISSUE THREAD

**Issue by HugoPlacer** [drwhut/tabletop-club#120]
**Is your feature request related to a problem? Please describe.**
I think it is useful to create community. In other hand, this will help to the developers with direct feedback, and they can provide help easily. Finally, I think people will share their custom games and this will improve the game a lot.

**Describe the solution you'd like**
Create an official discord server.

**Describe alternatives you've considered**
Create other types of channels to communicate with community like Reddit, Matrix…

**Additional context**
Thanks, I love your work, it's awesome!

**Comment by drwhut** [comment]
I agree with you, but there's one major road block that has prevented me from creating a community "server" so far: moderators.

For reasons that should hopefully not need explaining, I do not want to host a server/subreddit without moderators, and at the same time, I cannot expect moderators to "moderate" for free. I'll do some research at some point into how moderation works in services like Discord and Reddit, but for now I don't have the means necessary to hire a moderator.

P.S. Thank you for your kind words :heart:

**Comment by elmodor** [comment]
Hope it's okay if I chime in here. 

In my opinion a discord server usually grows with its community. It does not have to be perfect and it certainly won't need much moderation for a smaller community. When the community grows, so can the server.
Discord already has many security features you can use to tighten the server. There a multiple bots out there for auto moderation, role assignment etc. 
even if something happens, like some bot is going haywire somehow because it got access - then it might be an hour or two if a moderator peaks in and can act. I think that is totally fine for smaller communities/servers. 

The benefit would be to have a common place to talk, to exchange and maybe find some playmates. 

It is very humble and generous of you that you want to pay your moderators and I think that is a good thing to do! It just depends on the size of the community I would say. 

In the end: your project, your call. You have to be comfortable with what you choose.

> Thanks, I love your work, it's awesome!

I think we can all agree on this one :heart:

**Comment by drwhut** [comment]
> Discord already has many security features you can use to tighten the server. There a multiple bots out there for auto moderation, role assignment etc.

To be honest, I never really considered having bot moderators, I'll have to look up how effective they are.

Ultimately I would love to have a Discord server or a subreddit for the game, but I would prefer having someone else that I can trust be able to handle potential issues that can arise, since I'm not sure if I would be able to handle those situations (anxiety is a b****).

It's definitely food for thought, that's for sure!

**Comment by HugoPlacer** [comment]
I'm not an expert in Discord management and on Reddit I don't know anything, plus my English is not awesome, but I think I can manage this. Like the community of this game, atm is very little, and I don't think it will be so many problems in the near future. @elmodor you would like to be a moderator with me if @drwhut want?

**Comment by elmodor** [comment]
Discord is also not very privacy friendly. I'm not really a fan of Discord myself, however it is doing a good job in putting a community together.

Regarding issue and problem solving: I agree, it would be good if those would be accessible.

How about getting a community together, to find playmates/group plays - having a text and voice channel to do so? The channel feature for text and voice on discord is just not possible on matrix. Or is it now?
Also the possibility to screen share is sometimes very helpful.

Another alternative that I know of is Revolt - which is basically an open source discord clone. Very promising but I doubt that many people use it?

Do we need different types of services regarding development / problem solving and a general community get together?

**Comment by HugoPlacer** [comment]
I agree with @elmodor. I think Matrix is a good alternative to Discord (I use it daily). Furthermore, I choose Discord when I opened the Feature Request bc is the most popular app.

**Comment by GrimPixel** [comment]
Double servers mean double amount of work, ending up everyone joining both servers, in case they miss something.

**Comment by elmodor** [comment]
Not sure. I doubt the mainstream discord users uses matrix. And most matrix users probably don't use discord (that's why they use matrix).

Jitsi is a video chat platform / meetings. We are probably looking for an text/voice orientated solution with channel support.

**Comment by GrimPixel** [comment]
There is already a community of board games. You may have a look.
https://vassalengine.org/

**Comment by drwhut** [comment]
Apologies for the long wait, but I have an update to share! I've recently started to set up both a Discord server and a Matrix space (on matrix.org), and they're both nearly ready - I had a lot of time to think things over, and I've decided that starting off small and hiring moderators along the way is probably the best way to go, since we can grow a community organically that way with moderators that people know and trust.

However, I'm not 100% sure *how* soon they will be ready. My mental health has been somewhat shoddy as of late, so I'm not that confident in my ability to actively engage with the community as of right now. It is possible I could make the servers public now, but I feel that if I don't talk much in my own server, is that setting a good example? Having said that, I do want to at the very least have a community server ready before the release of v0.1.0 - it would be nice to celebrate the first stable release with people :)

So in the meantime, while I'm trying to get better I thought I'd share what the Discord server currently looks like, in the hopes that people give feedback on what channels they think would be a good addition, or if you think some of the channels are redundant:

```
Server:
    # welcome
    # rules
    # introductions
    # announcements
    # discord-announcements
    - discord-suggestions (Forum)

Tabletop Club:
    # general
    # questions
    # screenshots
    - support (Forum)
    # development

Board Games:
    - asset-packs (Forum)
    # board-game-discussion

Lobbies:
    # looking-for-players
    > Lobby 1 (Voice)
    > Lobby 2 (Voice)
    > Inactive (Voice)

Other:
    # game-discussion
    # godot
    # open-source
    # programming
    # memes
```

**Comment by harkamalsr** [comment]
> So in the meantime, while I'm trying to get better I thought I'd share what the Discord server currently looks like, in the hopes that people give feedback on what channels they think would be a good addition, or if you think some of the channels are redundant:
> 
> ```
> Server:
>     # welcome
>     # rules
>     # introductions
>     # announcements
>     # discord-announcements
>     - discord-suggestions (Forum)
> 
> Tabletop Club:
>     # general
>     # questions
>     # screenshots
>     - support (Forum)
>     # development
> 
> Board Games:
>     - asset-packs (Forum)
>     # board-game-discussion
> 
> Lobbies:
>     # looking-for-players
>     > Lobby 1 (Voice)
>     > Lobby 2 (Voice)
>     > Inactive (Voice)
> 
> Other:
>     # game-discussion
>     # godot
>     # open-source
>     # programming
>     # memes
> ```

An specifically designated off-topic channel could be nice, but other than that this looks great! Also what's the difference between announcements and discord-announcements?

**Comment by drwhut** [comment]
> An specifically designated off-topic channel could be nice

Yeah, that makes sense! Adding it now...

> Also what's the difference between announcements and discord-announcements?

`announcements` are for the game itself, and will most likely be used for announcing new releases of the game. `discord-announcements` are specifically for the Discord server, e.g. new channels, new rules, permission changes, etc.

**Comment by elmodor** [comment]
Looks good! If you start something you either don't do it or do it 100%. I doubt many Discord server started out so organized. Well done :)

**Comment by harkamalsr** [comment]
> `announcements` are for the game itself, and will most likely be used for announcing new releases of the game. `discord-announcements` are specifically for the Discord server, e.g. new channels, new rules, permission changes, etc.

Okay perfect, that makes sense to me!

This is better organized than most servers I'm in, I'm sure it will be great

:D

**Comment by GrimPixel** [comment]
Your mental problem? I can guess it's about money. When we have a server, we can discuss it at ease.

**Comment by drwhut** [comment]
Ladies and gentlemen, the flood gates are open!

- https://discord.gg/GqYkGV4WwX
- https://matrix.to/#/!dbNhzKYPHpcgZgUkRi:matrix.org?via=matrix.org
