### ISSUE TITLE
Multiple "Players" in Single Player.

### ISSUE THREAD

**Issue by hansonry** [drwhut/tabletop-club#126]
**Is your feature request related to a problem? Please describe.**
Not really, it is more of a marketing/testing feature. It might be helpful for a single player to simulate more than one player for the purposes of testing or demoing the game to themselves or others.

**Describe the solution you'd like**
Sometime between selecting single player and "playing" a game, set the number of players. Either by adding an intermediate screen or a way to add/remove "hands" while on the table.

**Describe alternatives you've considered**
I thought about opening the client multiple times and creating a multiplayer game to test out what gameplay would be, but it seems like a lot of work.

**Comment by elmodor** [comment]
Just for clarification:
Do you want to have multiple players active at the same time, or the option to "swap seat" to swap to another player/hand/color? Or both?

**Comment by hansonry** [comment]
I was thinking more of the "swap seat", but I would be fine with both.

**Comment by drwhut** [comment]
Honestly, the workaround you mentioned of running the game multiple times is what I do to test the multiplayer anyways - in each instance you can go to the options menu and change the name and colour of that player.

Since the use cases are pretty niche, I think the workaround is worth doing for now. I can always reopen the issue if there is enough demand for it!
