### ISSUE TITLE
Use TSV instead of cfg files

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#158]
TSV will be more convenient and compact than the current cfg.

```
[52-Card Deck]
name = "52 speelkaarten"
desc = "52 Franse speelkaarten, exclusief jokers."

[Ace of Clubs]
name = "Klaverenaas"
desc = "Een Franse speelkaart."
```
```
52-Card Deck	52 speelkaarten	52 Franse speelkaarten, exclusief jokers.
Ace of Clubs	Klaverenaas	Een Franse speelkaart.
```

**Comment by youkaicountry** [comment]
It more be more compact, but I do not think this would be more convineient.
It would force the user to give a value for every possible variable, and enforce strict ordering.
It would also make the files a bit confusing to work with for a human, since to know what value you are modifying you would have to keep track of which column is being modified.

**Comment by GrimPixel** [comment]
It can work for locales. The first row can be ignored by the program.
```
	name	desc
52-Card Deck	52 speelkaarten	52 Franse speelkaarten, exclusief jokers.
Ace of Clubs	Klaverenaas	Een Franse speelkaart.
```

**Comment by elmodor** [comment]
I also find TSV more difficult to read.
Guess I am used to the current config layout because it is often used.

**Comment by drwhut** [comment]
I agree, it is somewhat hard to read. As was mentioned, the only tangible benefit for the new format would be it's compactness, but IMO the current system isn't "bloated". Plus, it is consistent with the other configuration files the game uses, and it is a well-known standard (INI).
