### ISSUE TITLE
Change the icon colour

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#164]
The icons are black and inconspicuous. They can be white, like texts.

**Comment by elmodor** [comment]
I assume you mean the icons in the main menu on the bottom?

**Comment by GrimPixel** [comment]
I meant all black icons, including those on the left side.

**Comment by elmodor** [comment]
I agree those are a bit difficult to read.

The icons in the main menu (on the bottom) should maybe have a suble whit-ish color. Not as white as the buttons because the user focus should be on the main menu buttons not om the icons. So using a more suble color there reduces the focus on the elements.

Examples:
Color f0f0f0
![game_f0f0f0](https://user-images.githubusercontent.com/2340082/205502452-6d6a88c8-6ced-4a09-b927-05c20578c9b5.png)
![menu_f0f0f0](https://user-images.githubusercontent.com/2340082/205502453-8bcc9a23-7aea-44ca-81cc-79e992389965.png)

Color afafaf
![game_afafaf](https://user-images.githubusercontent.com/2340082/205502443-c6aa71cc-487f-43c0-824f-39d9991d98df.png)
![menu_afafaf](https://user-images.githubusercontent.com/2340082/205502445-cc039a67-721f-4809-9c0c-e0a58c53c806.png)

**Comment by drwhut** [comment]
I agree, the colours could be changed. But I'm not sure if they should be bright, like in the first example. I have a few friends who know a thing or two about this, so I'll ask for their advice.

**Comment by GrimPixel** [comment]
Maybe they together with other elements should hide, like in Far Cry 2.
