### ISSUE TITLE
Piece flies out

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#166]
**Describe the bug**
Piece flies out

**To Reproduce**
Left-clicking on a piece and hold for a moment, it will be accelerated and if stopped holding during the acceleration, the piece will fly out of the scene.

**Additional context**
Maybe highlighting the piece instead of moving it upwards is better.

**Comment by elmodor** [comment]
#140 fixed that the piece is only going up when hovering, so it should not fly off the table anymore.

I think it's fine that the hover moves the piece a bit up, because if it doesn't you would need to move it up manually all the time when you want to move something - and that's why you hold the piece anyways.

But the acceleration needs to be fixed.
So whenever `stop_hovering` is called we need to make sure that we don't keep the current `angular_velocity` - since we stop the hover and the hover_position is not used anymore but the `angular_velocity` seems to be kept.

**Comment by GrimPixel** [comment]
Yes, lifting it a bit looks good. The improvement could be specifying the lift and drop distance, to make sure the piece doesn't collide with other pieces and doesn't fall after dropping.
If the velocity is horizontal, then it's throwing.

**Comment by elmodor** [comment]
Yeah it was a bit late yesterday. Resetting the `linear_velocity` in Y should suffice.
