### ISSUE TITLE
Cards collide weirdly in mid-air.

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#194]
1. Load “Poker”
2. Put the deck in hand
3. Throw the whole deck forward

Then we can see only some of the cards actually fly forwards.

**Comment by drwhut** [comment]
This is a known issue with the physics engine in Godot.

I'll label this as a bug, but I can't guarantee this can be fixed any time soon.

**Comment by drwhut** [comment]
Turns out this wasn't an issue with Godot, upon closer inspection I noticed that the only cards that stopped moving were ones that merged with other cards to form stacks, so the reason some cards stopped moving when thrown forward was because the stacks started out with no velocity. There's still a slight "pause" as the game resolves the collisions and creates the stacks, but all of the cards now fly forwards as expected.
