### ISSUE TITLE
Precompiled Binaries of modified Godot

### ISSUE THREAD

**Issue by Banbury** [drwhut/tabletop-club#250]
**Is your feature request related to a problem? Please describe.**
I want to make changes to tabletop-club, but I don't want to compile Godot.

**Describe the solution you'd like**
Could you provide precompiled binaries of your Godot fork?

**Comment by drwhut** [comment]
I'll consider this for sure - the fork conveniently creates editor builds whenever commits are pushed, so it would just be a matter of hosting those somewhere (not 100% sure if they should be hosted on GitHub, since the editor builds are somewhat bigger than the release ones, and old builds of the engine would become irrelevant).

**Comment by drwhut** [comment]
I've added a note to the documentation about downloading pre-built binaries, which will be available once v0.1.0-beta4 is released :+1:
