### ISSUE TITLE
To create boards like cards

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#266]
Boards are mostly just like cards and are thicker, so it could be created that way.

**Comment by drwhut** [comment]
Boards and cards have a fundamental difference that make this impossible: boards are made with custom 3D models, as to allow for the creation of game boards that are not necessarily rectangular (e.g. crokinole), whereas cards need to be rectangular in shape in order to be able to stack with each other.

I vaguely remember there being talk about having generic "templates" available somewhere for 3D assets, which would be helpful in creating simple, rectangular boards like you described. #115 is also planned for v0.2.0, which could potentially be extended to multiple different types of objects? Will need to have a think about that.
