### ISSUE TITLE
Slower image loading than before

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#267]
Comparing to Beta 3, images are loaded slower. This increases the chance of freezing when flipping object pages quickly.

**Comment by drwhut** [comment]
This will be due to the workaround in dcb084d9b281cf6412d6a7775a0ff1ef2da3b852, but after some further testing, the workaround doesn't seem to work 100% of the time... I'm getting freezing in both Beta 4 and RC 1, I think I might have gotten lucky when testing the fix when it was first implemented.

I might end up removing the workaround if it doesn't help with the freezing that much since it leads to longer loading times, like you said in this issue and in #265.

**Comment by drwhut** [comment]
After some further testing both with and without the workaround, it looks like the game lasts on average twice as long before freezing with the workaround included. So I've decided to keep it in for now even if it doesn't fully fix the freezing. v0.2.0 will have a revamped objects menu which should remove the root issue altogether.
