### ISSUE TITLE
Separate the speaker function from the timer

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#271]
**Is your feature request related to a problem? Please describe.**
Timers are not bound to be able to play music. I think the object “Radio” can be placed in “Speaker”, and use https://opengameart.org/content/alarm-clock for the “Timer”.

**Comment by drwhut** [comment]
Timers are a subclass of Speakers because they also have the ability to play sounds, particularly when the countdown reaches 0. One does not necessarily need to use the "Speaker" menu when interacting with a Timer, it's just there so if you want a track to start playing when the timer reaches 0, then you can do so.

On the alarm clock you linked, I actually tried to include that model when I first implemented timers, but I could not get it to work at all. I think the Blender file was too out-of-date, so I gave up and looked for other models.

**Comment by GrimPixel** [comment]
I think it could be “Speaker and Timer” then, since Timers are more useful. The phonograph can also be a timer with modifications today.
