### ISSUE TITLE
Can't get pass loading screen when opening project inside of Godot tabletop-3.5.3

### ISSUE THREAD

**Issue by GustavoLR548** [drwhut/tabletop-club#319]
**Describe the bug**
I'm trying to run the project inside of the Godot Engine, but I can't get pass the loading screen, as if the game it is stuck loading its assets.

**To Reproduce**
1. Compiled the Godot Engine as specified the in the documentation 
2. https://docs.godotengine.org/en/3.6/development/compiling/compiling_for_x11.html
3. I used the tabletop-3.5.3 version
4. Remembered to add the godot module (I installed the master branch)
5. Compiled everything using ```scons platform=x11```
6. Cloned the tabletop_club project from the source code of version 0.1.2
7. Opened in Custom Godot.
8. Click on "Launch"
9. Infinite loading screen appeared

**Expected behavior**
It was suppose to take me to the menu screen, but it instead it is stuck on the "LoadingScreen.tscn"

**Screenshots**
This is the point where the game is stuck
![stuckon-loading-screen](https://github.com/user-attachments/assets/4e807e72-d48d-478f-b034-a34a63fbd773)

Here is the terminal output:
![terminal-output](https://github.com/user-attachments/assets/fdedc67b-9f53-45e3-b4a3-051f4d7cb7d0)

Here is the lines in question, first is 1343
![image](https://github.com/user-attachments/assets/4a222b57-bd39-4e52-ae4d-25bebb14e640)

and here is 511
![image](https://github.com/user-attachments/assets/351c4431-3ad1-49f6-b149-300d3b994409)

**Environment**
Linux 6.10.1-arch1-1 Gnome, Wayland

**Version**
Godot Version: tabletop-3.5.3 (from drwhut/godot)
Module version: tabletop-club-godot-module (master branch)

If I forgot anything, please let me know

**Comment by drwhut** [comment]
First things first, v0.1.2 of Tabletop Club uses the `tabletop-3.4.5` branch of my custom fork of Godot, not `tabletop-3.5.3` (which is only being used in the development of v0.2.0).

Secondly, I think the reason you're getting that error is because of a mismatched module version - the custom module went through a re-write for v0.2.0, and so the current `master` version will *not* work with v0.1.2.

To be absolutely safe, you can use this command to download the right branch, including the right version of the custom module:
```bash
git clone --depth 1 --recursive https://github.com/drwhut/godot.git -b tabletop-3.4.5
```
It sounds like you have already found the documentation, but [here](https://tabletop-club.readthedocs.io/en/stable/general/download/compiling_from_source.html#compiling-from-the-source-code) is a link to the stable version of the docs, which should work for the version of the game you're trying to compile.

Let me know if this works!

**Comment by GustavoLR548** [comment]
Oh wow, thanks for the quick response! I'll definitely follow the steps you provided and check if everything works correctly. I'll update you with the results as soon as I have them.

**Comment by GustavoLR548** [comment]
> First things first, v0.1.2 of Tabletop Club uses the `tabletop-3.4.5` branch of my custom fork of Godot, not `tabletop-3.5.3` (which is only being used in the development of v0.2.0).
> 
> Secondly, I think the reason you're getting that error is because of a mismatched module version - the custom module went through a re-write for v0.2.0, and so the current `master` version will _not_ work with v0.1.2.
> 
> To be absolutely safe, you can use this command to download the right branch, including the right version of the custom module:
> 
> ```shell
> git clone --depth 1 --recursive https://github.com/drwhut/godot.git -b tabletop-3.4.5
> ```
> 
> It sounds like you have already found the documentation, but [here](https://tabletop-club.readthedocs.io/en/stable/general/download/compiling_from_source.html#compiling-from-the-source-code) is a link to the stable version of the docs, which should work for the version of the game you're trying to compile.
> 
> Let me know if this works!

Hi!

Just as a heads up, I was able to successfully compile and run Tabletop Club with no issues, thanks to your support :)

Some things that I would like to say before closing this issue

1 - I had a strange problem, were a thirdparty library called "vhacd" was returning some problems during compilation, It was accusing of a missing import in the file "vhacdlCHull.h". I just added the import and it fixed everything. I don't know how this happened, but I thought it was relevant to mention.
2 - This information of which versions of the game, the godot and module could be more explicit explained in the documentation. Even with this page [here](https://tabletop-club.readthedocs.io/en/stable/general/download/compiling_from_source.html#compiling-from-the-source-code) I was still very much confused on which version I should use. Maybe adding a reference table or something would already help, like this.

| Godot version  | Tabletop version | Module        |
|----------------|------------------|---------------|
| tabletop-3.4.x | 0.1.x            | 3.4           |
| tabletop-3.5.x | 0.2.x            | master branch |

Once again, thank you very much for your help, and have a very nice day :+1:

**Comment by drwhut** [comment]
Glad to hear it! :grin:

I'm not sure what to make of the `vhacd` issue, I've never personally encountered it myself - maybe it's something to do with the way it's installed on your distribution? Out of interest, which distribution do you use?

At some point when the `0.2-rewrite` branch gets merged into `master` (hopefully sooner rather than later...), I was planning to revisit the entire documentation, so I'll definitely keep your recommendation in mind, as it would make it explicitly clear which Godot branch should be used for which Tabletop Club version :+1:

**Comment by GustavoLR548** [comment]
Hey!

It's possible that my distribution might be part of the reason. To answer your question, I use [Crystal Linux](https://getcryst.al/site).

I'm excited to see what the 0.2 update will bring. The project is in great hands, so I'm expecting some great improvements. If the opportunity arises (and I have the right skills), I'd love to contribute to the source code or documentation. 😅

Have a great day!
